### PR TITLE
Fix code-block Indentation

### PR DESCRIPTION
**Pull request by nirmitjoshi**
The pull request resolves a YAML parsing error encountered when attempting to paste code from the README into the config.yml. The issue was caused by suboptimal code block indentation in the README, resulting in YAML parsing issues.

**Changes Made:**
- Adjusted the indentation of the code block within the README.
- Ensured proper YAML formatting to prevent errors when copying the code into the config.yml

### CODE REVIEW

**Comment by nullishamy** [comment]
Did they change the default spacing from 4 to 2? This was already fixed by someone in another PR so wondering why it's broken again 🤔.

**Comment by nirmitjoshi** [comment]
No, in YAML, the indentation is not fixed to either 4 or 2 spaces. YAML is flexible in terms of the number of spaces used for indentation. However, in the previous code block, the issue was that tabs were used instead of spaces for indentation. YAML specifically mandates spaces, not tabs.

Regarding the previous PR you mentioned:
What I see now is that the code block is nested within a list, which itself is further indented inside a toggle. This nesting structure might be causing the appearance of tabs. But I don't really know why it worked then and not now.

**Comment by nullishamy** [comment]
Alright, I guess. I'll merge this one, but honestly I'm pretty tempted to just reject future PRs to this area because it's needlessly annoying.

**Comment by nirmitjoshi** [comment]
> Alright, I guess. I'll merge this one, but honestly I'm pretty tempted to just reject future PRs to this area because it's needlessly annoying.

yeah, agree

**Pull request merged**
