### PR TITLE
doc: clarify theme change process in lazygit config.yml

### PR DESCRIPTION
**Pull request by shamindras**
@nullishamy per the discussion in #2, specifically per [this comment](https://github.com/catppuccin/lazygit/issues/2#issuecomment-1368159014).

- [x] Updated the `README.md`. 
- [x] Fixed minor markdown linting issues.

Please let me know if there are any further changes you would like me to make.

### CODE REVIEW

**Comment by nullishamy** [comment]
Are the theme keys case sensitive? You lower-cased them all, so it would make sense to be consistent. The example config from lg has it in the case shown in this repo.

**Comment by shamindras** [comment]
> Are the theme keys case sensitive? You lower-cased them all, so it would make sense to be consistent. The example config from lg has it in the case shown in this repo.

nice catch! I've updated in the [latest commit](https://github.com/catppuccin/lazygit/pull/3/commits/353b53addc4359109093dce8001b60c47f0aede2)

**Review by nullishamy — APPROVED** [review]
LGTM - thanks for the contribution!

**Comment by shamindras** [comment]
> LGTM - thanks for the contribution!

thank you for creating this theme, and your patient help with the PR.

**Pull request merged**
