### PR TITLE
chore: CI validates themes using the lazygit config schema

### PR DESCRIPTION
**Pull request by sp3ctum**
The latest version of the schema is used. This means the color schemes in this repository are implicitly meant to be used in the latest lazygit development version.

The schema version could also be locked to a recent release, but at this time there is no nice way of resolving the latest version in the validation logic (github action).

Example of the workflow runs:
https://github.com/sp3ctum/lazygit/actions/workflows/validate-yaml.yml

---

I also noticed the schema validation complains an extra property is used in many files. I'll look into why this might be - I suppose the lazygit schema might have changed after the colorschemes were created in this repository.

### CODE REVIEW

**Comment by sp3ctum** [comment]
Ok, looks like the `selectedRangeBgColor` configuration option was removed here some weeks ago:
https://github.com/jesseduffield/lazygit/commit/f3eb180f75496637719895902abf76af10b8425f

I wonder what would be the best way to handle this change. 😄 

Since this is a recent addition, most people are probably not using a version that has this change. However, the validation I added uses the bleeding edge version of the schema to validate the colorschemes.

What would you like to do? Here are some options:

1. use the schema from the latest lazygit release. I can maybe add some logic to the job to figure this out
2. remove validation in CI
3. remove validation in CI, and add a "best effort system" using yaml-language-server

Regarding option 3, this is what I use personally:
image

[yaml-language-server](https://github.com/redhat-developer/yaml-language-server/tree/main) is included in many plugins by default. The way it works is, you provide the schema using this magic comment, and then you get nice features:
- validation
- documentation
- autocompletion

<details><summary>Example of documentation</summary>
<p>

image


</p>
</details>

**Comment by nullishamy** [comment]
Hi! Thanks for opening this, I do really like this idea.

The CI itself looks fine, does the job. Just need to figure out what to do with regard to the versioning.
I did propose elsewhere some time ago that we should look to version this repo in accordance with lazygit releases.

I think we should continue along this idea, as I doubt many people are running bleeding edge versions of lazygit. We should strive to publish configs for past versions (whereby we only maintain the latest version).

So, if we do that, we can simple change the build script to build without that key and archive the old version into a directory within the repo.

As an aside, it'd be pretty nice to have that yaml-server put into our generated configs, I think.

**Comment by sp3ctum** [comment]
Ok, glad you like the idea!

Right now the latest version of lazygit is `v0.40.2`, released 2023-08-07 ([lazygit releases page](https://github.com/jesseduffield/lazygit/releases)).

Lazygit started publishing the json schema a couple of months after the latest release, on 2023-12-23 ([lazygit/schema/config.json history](https://github.com/jesseduffield/lazygit/commits/master/schema/config.json))

I think this means the following:
- what I have added in this PR shows that for the bleeding edge (unreleased) version, the colorschemes contain an extra setting that will probably just get ignored (I am running bleeding edge and my catpuccin colorscheme does work)
- my guess is that using the first version of the schema can be used to validate the current colorschemes just fine, although _technically_ the schema wasn't available when the most recent release was made

**Comment by sp3ctum** [comment]
I may have some time to contribute this change as a suggestion. 🤞🏻

**Comment by sp3ctum** [comment]
Ok, I made it explicit on the code level that the current version for the colorschemes is the latest release.

I experimented a little and found out it's actually possible to warn the developer when keys are mistyped. Further improvements are also possible and I can work on them if you'd like.

image

Let me know what you think!

**Comment by nullishamy** [comment]
After some discussion with people in the Catppuccin Discord, it would probably be better to utilise Git[Hub] features and tooling to handle theme versions. Using tags/releases for each lazygit version (that mandates config changes) seems like the most sane way to go about this. 

As a result, we would have to employ a tool to build releases for us (Catppuccin uses release-please currently), and I think that building our theme in CI (with whiskers, a templating tool build by Catppuccin) alongside this validation (as a sanity check for the release) would be an ideal solution for us. 

On the topic of the validation, I don't think that we should necessarily halt a release on validation fail (if, say, we need to amend an old release etc.), but it would work well as a guard rail against completely faulty releases.

As for release-please, I think their `simple` format would be ideal for us. (https://github.com/googleapis/release-please#strategy-language-types-supported for more info).

Along with these ideas, we should fully remove the build.ts file, as it is no longer required.

**Comment by nullishamy** [comment]
Release-please is now setup. After doing all of that, I think CI validation is probably overkill for our purposes. I still added the yaml-language-server comment as that will help with local development a lot. Appreciate you going out of your way to find out about the schema, and provide an example for how to integrate it with the LSP!

**Pull request closed without merging**
